# Generated by Django 4.2.13 on 2026-06-02 20:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICD10Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_range_start', models.CharField(help_text='Örn: A00', max_length=10, verbose_name='Başlangıç Kodu')),
                ('code_range_end', models.CharField(help_text='Örn: B99', max_length=10, verbose_name='Bitiş Kodu')),
                ('name', models.CharField(help_text='Örn: Belirli Enfeksiyöz ve Paraziter Hastalıklar', max_length=255, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'ICD-10 Kategorisi',
                'verbose_name_plural': 'ICD-10 Kategorileri',
                'db_table': 'icd10_category',
                'ordering': ['code_range_start'],
            },
        ),
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Örn: J18.9', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='ICD-10 kodu geçersiz format. Örnek: A01, B23.4, C45.67', regex='^[A-Z][0-9]{2}(\\.[0-9A-Z]{1,4})?$')], verbose_name='ICD-10 Kodu')),
                ('name', models.CharField(help_text='Örn: Pnömoni, tanımlanmamış', max_length=500, verbose_name='Tanı Adı')),
                ('description', models.TextField(blank=True, help_text='Hastalığın klinik tanımı. NLP için yapılandırılmış metin.', verbose_name='Klinik Açıklama')),
                ('keywords', models.TextField(blank=True, help_text='NLP eşleştirme için: pnömoni, akciğer iltihabı, ateş...', verbose_name='Anahtar Kelimeler')),
                ('severity', models.CharField(choices=[('LOW', 'Düşük Risk'), ('MODERATE', 'Orta Risk'), ('HIGH', 'Yüksek Risk'), ('CRITICAL', 'Kritik')], default='MODERATE', max_length=10, verbose_name='Klinik Ağırlık')),
                ('is_active', models.BooleanField(default=True, help_text='Artık kullanılmayan kodlar için False yapın.', verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='icd10.icd10category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'ICD-10 Kodu',
                'verbose_name_plural': 'ICD-10 Kodları',
                'db_table': 'icd10_code',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_type', models.CharField(choices=[('STANDARD', 'Standart Protokol'), ('EMERGENCY', 'Acil Protokol'), ('PEDIATRIC', 'Pediatrik Protokol'), ('GERIATRIC', 'Geriatrik Protokol')], default='STANDARD', max_length=20, verbose_name='Protokol Türü')),
                ('name', models.CharField(help_text='Örn: Toplum Kökenli Pnömoni - Standart Tedavi Protokolü', max_length=300, verbose_name='Protokol Adı')),
                ('min_recovery_days', models.PositiveIntegerField(help_text='Beklenen minimum taburculuk süresi', verbose_name='Min. İyileşme Süresi (gün)')),
                ('max_recovery_days', models.PositiveIntegerField(help_text='Beklenen maksimum taburculuk süresi', verbose_name='Max. İyileşme Süresi (gün)')),
                ('clinical_thresholds', models.JSONField(blank=True, default=dict, help_text='Kural motoru için sayısal eşik değerleri (JSON)', verbose_name='Klinik Eşik Değerleri')),
                ('required_steps', models.JSONField(blank=True, default=list, help_text='Sıralı ve zorunlu klinik adımlar (JSON listesi)', verbose_name='Zorunlu Tedavi Adımları')),
                ('first_line_medications', models.TextField(blank=True, help_text='Protokol gereği önerilen ilaçlar (virgülle ayrılmış)', verbose_name='Birinci Basamak İlaçlar')),
                ('contraindications', models.TextField(blank=True, verbose_name='Kontrendikasyonlar')),
                ('reference_guideline', models.CharField(blank=True, help_text='Örn: WHO 2023, Türk Toraks Derneği Pnömoni Rehberi', max_length=500, verbose_name='Kaynak Kılavuz')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Protokol Versiyonu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icd10_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='icd10.icd10code', verbose_name='ICD-10 Tanısı')),
            ],
            options={
                'verbose_name': 'Tedavi Protokolü',
                'verbose_name_plural': 'Tedavi Protokolleri',
                'db_table': 'treatment_protocol',
                'ordering': ['icd10_code', 'protocol_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='treatmentprotocol',
            constraint=models.UniqueConstraint(fields=('icd10_code', 'protocol_type', 'version'), name='unique_protocol_per_code_type_version'),
        ),
        migrations.AddIndex(
            model_name='icd10code',
            index=models.Index(fields=['code'], name='icd10_code_code_c8981c_idx'),
        ),
        migrations.AddIndex(
            model_name='icd10code',
            index=models.Index(fields=['severity'], name='icd10_code_severit_96437f_idx'),
        ),
    ]
