# Generated by Django 4.2.13 on 2026-06-02 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icd10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_identity_hash', models.CharField(help_text='Ham TC NO saklanmaz. SHA-256 hash değeri tutulur.', max_length=64, unique=True, verbose_name='TC Kimlik Hash (SHA-256)')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('date_of_birth', models.DateField(verbose_name='Doğum Tarihi')),
                ('gender', models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadın'), ('O', 'Diğer / Belirtilmemiş')], max_length=1, verbose_name='Cinsiyet')),
                ('blood_type', models.CharField(choices=[('A+', 'A Rh+'), ('A-', 'A Rh-'), ('B+', 'B Rh+'), ('B-', 'B Rh-'), ('AB+', 'AB Rh+'), ('AB-', 'AB Rh-'), ('O+', '0 Rh+'), ('O-', '0 Rh-'), ('UNK', 'Bilinmiyor')], default='UNK', max_length=4, verbose_name='Kan Grubu')),
                ('chronic_conditions', models.TextField(blank=True, help_text='Diyabet, hipertansiyon vb. — NLP için serbest metin', verbose_name='Kronik Hastalıklar')),
                ('known_allergies', models.TextField(blank=True, help_text='İlaç, besin alerjileri — NLP için serbest metin', verbose_name='Bilinen Alerjiler')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hasta',
                'verbose_name_plural': 'Hastalar',
                'db_table': 'patient',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['tc_identity_hash'], name='patient_tc_iden_8a0bac_idx'), models.Index(fields=['date_of_birth'], name='patient_date_of_8742a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.CharField(choices=[('EMERGENCY', 'Acil'), ('ELECTIVE', 'Elektif (Planlanmış)'), ('TRANSFER', 'Transfer'), ('OUTPATIENT', 'Ayakta Tedavi')], max_length=20, verbose_name='Başvuru Türü')),
                ('admission_date', models.DateTimeField(verbose_name='Yatış Tarihi')),
                ('discharge_date', models.DateTimeField(blank=True, null=True, verbose_name='Taburculuk Tarihi')),
                ('discharge_type', models.CharField(choices=[('RECOVERED', 'İyileşerek Taburcu'), ('TRANSFERRED', 'Transfer ile Taburcu'), ('AOR', 'İsteğe Bağlı Taburcu (İmzalı Red)'), ('DECEASED', 'Exitus'), ('ADMITTED', 'Hâlâ Yatıyor')], default='ADMITTED', max_length=20, verbose_name='Taburculuk Türü')),
                ('ward', models.CharField(blank=True, help_text='Örn: Göğüs Hastalıkları, Kardiyoloji', max_length=100, verbose_name='Klinik / Servis')),
                ('bed_number', models.CharField(blank=True, max_length=20, verbose_name='Yatak No')),
                ('notes', models.TextField(blank=True, verbose_name='Genel Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitting_physician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to=settings.AUTH_USER_MODEL, verbose_name='Kabul Eden Hekim')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='patients.patient', verbose_name='Hasta')),
                ('primary_diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_admissions', to='icd10.icd10code', verbose_name='Ana Tanı (ICD-10)')),
                ('secondary_diagnoses', models.ManyToManyField(blank=True, related_name='secondary_admissions', to='icd10.icd10code', verbose_name='Ek Tanılar')),
            ],
            options={
                'verbose_name': 'Yatış',
                'verbose_name_plural': 'Yatışlar',
                'db_table': 'admission',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('EPICRISIS', 'Epikriz (Taburculuk Özeti)'), ('CONSULTATION', 'Konsültasyon Notu'), ('OPERATION', 'Ameliyat Notu'), ('RADIOLOGY', 'Radyoloji Raporu'), ('PATHOLOGY', 'Patoloji Raporu'), ('PROGRESS', 'Günlük Takip Notu')], default='EPICRISIS', max_length=20, verbose_name='Rapor Türü')),
                ('report_date', models.DateTimeField(verbose_name='Rapor Tarihi')),
                ('complaint', models.TextField(blank=True, help_text='Hastanın başvuru şikayeti (serbest metin)', verbose_name='Şikayet')),
                ('history_of_present_illness', models.TextField(blank=True, verbose_name='Hastalık Öyküsü')),
                ('physical_examination', models.TextField(blank=True, verbose_name='Fizik Muayene Bulguları')),
                ('laboratory_results', models.TextField(blank=True, help_text="Serbest metin; ileride JSON'a dönüştürülecek", verbose_name='Laboratuvar Sonuçları')),
                ('imaging_results', models.TextField(blank=True, help_text='Röntgen, BT, MR, USG raporları', verbose_name='Görüntüleme Sonuçları')),
                ('clinical_course', models.TextField(blank=True, help_text='Yatış süresince hastalığın seyri', verbose_name='Klinik Seyir')),
                ('discharge_summary', models.TextField(blank=True, verbose_name='Taburculuk Özeti')),
                ('discharge_medications', models.TextField(blank=True, help_text='Reçete edilen ilaçlar (serbest metin)', verbose_name='Taburculuk İlaçları')),
                ('follow_up_instructions', models.TextField(blank=True, verbose_name='Kontrol Talimatları')),
                ('raw_text', models.TextField(blank=True, help_text="OCR/NLP pipeline'ı için işlenmemiş metin", verbose_name='Ham Rapor Metni')),
                ('nlp_processed', models.BooleanField(default=False, verbose_name='NLP İşlendi mi?')),
                ('nlp_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='NLP İşlem Tarihi')),
                ('is_finalized', models.BooleanField(default=False, help_text='True ise rapor değiştirilmez (imzalı)', verbose_name='Sonuçlandırıldı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_reports', to='patients.admission', verbose_name='Yatış')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_reports', to=settings.AUTH_USER_MODEL, verbose_name='Raporun Yazarı (Hekim)')),
            ],
            options={
                'verbose_name': 'Klinik Rapor',
                'verbose_name_plural': 'Klinik Raporlar',
                'db_table': 'clinical_report',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['admission', 'report_type'], name='clinical_re_admissi_c9e960_idx'), models.Index(fields=['nlp_processed'], name='clinical_re_nlp_pro_9c5f0a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['patient', 'admission_date'], name='admission_patient_6c3267_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['primary_diagnosis'], name='admission_primary_8329a4_idx'),
        ),
    ]
