# Generated by Django 4.2.13 on 2026-06-02 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icd10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(help_text='Örn: Laparoskopik Apendektomi', max_length=300, verbose_name='Prosedür Adı')),
                ('procedure_code', models.CharField(blank=True, max_length=50, verbose_name='Prosedür Kodu (ICD-10-PCS)')),
                ('status', models.CharField(choices=[('PLANNED', 'Planlandı'), ('PERFORMED', 'Uygulandı'), ('CANCELLED', 'İptal Edildi'), ('POSTPONED', 'Ertelendi')], default='PLANNED', max_length=15, verbose_name='Durum')),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Planlanan Tarih/Saat')),
                ('performed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Gerçekleştirildiği Tarih/Saat')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (dakika)')),
                ('complications', models.TextField(blank=True, help_text='İşlem sırasında/sonrasında gelişen komplikasyonlar', verbose_name='Komplikasyonlar')),
                ('notes', models.TextField(blank=True, verbose_name='Operatör Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='patients.admission', verbose_name='Yatış')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_procedures', to=settings.AUTH_USER_MODEL, verbose_name='Uygulayan Hekim')),
            ],
            options={
                'verbose_name': 'Klinik Prosedür',
                'verbose_name_plural': 'Klinik Prosedürler',
                'db_table': 'clinical_procedure',
                'ordering': ['-scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AppliedProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('compliance_score', models.FloatField(blank=True, help_text='0-100 arası; kural motoru tarafından otomatik hesaplanır', null=True, verbose_name='Uyum Skoru (%)')),
                ('compliance_calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Skor Hesaplama Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Hekim Notu')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_protocols', to='patients.admission', verbose_name='Yatış')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_instances', to='icd10.treatmentprotocol', verbose_name='Seçilen Protokol')),
                ('selected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Protokolü Seçen Hekim')),
            ],
            options={
                'verbose_name': 'Uygulanan Protokol',
                'verbose_name_plural': 'Uygulanan Protokoller',
                'db_table': 'applied_protocol',
            },
        ),
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(help_text='Örn: Amoksisilin-Klavulanik Asit', max_length=300, verbose_name='İlaç Adı')),
                ('drug_code', models.CharField(blank=True, help_text='ATC sınıflandırması veya ürün barkodu', max_length=50, verbose_name='ATC/Barkod Kodu')),
                ('dose', models.CharField(help_text='Örn: 1g, 500mg, 2 ünite', max_length=100, verbose_name='Doz')),
                ('route', models.CharField(choices=[('PO', 'Oral (Ağızdan)'), ('IV', 'İntravenöz (Damardan)'), ('IM', 'İntramusküler (Kas içine)'), ('SC', 'Subkütan (Deri altı)'), ('TOP', 'Topikal'), ('INH', 'İnhalasyon'), ('PR', 'Rektal'), ('OTH', 'Diğer')], max_length=5, verbose_name='Uygulama Yolu')),
                ('frequency', models.CharField(help_text='Örn: 2x1, 3x1, 12 saatte bir', max_length=100, verbose_name='Sıklık')),
                ('start_datetime', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('status', models.CharField(choices=[('ORDERED', 'Orderlanmış'), ('ADMINISTERED', 'Uygulandı'), ('SKIPPED', 'Atlandı / Uygulanmadı'), ('CANCELLED', 'İptal Edildi')], default='ORDERED', max_length=15, verbose_name='Durum')),
                ('skip_reason', models.TextField(blank=True, verbose_name='Atlanma / İptal Nedeni')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_medications', to=settings.AUTH_USER_MODEL, verbose_name='Uygulayan (Hemşire/Hekim)')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.admission', verbose_name='Yatış')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_medications', to=settings.AUTH_USER_MODEL, verbose_name='Orderlayen Hekim')),
            ],
            options={
                'verbose_name': 'İlaç Kaydı',
                'verbose_name_plural': 'İlaç Kayıtları',
                'db_table': 'medication_record',
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['admission', 'status'], name='medication__admissi_122020_idx'), models.Index(fields=['drug_name'], name='medication__drug_na_3c138f_idx')],
            },
        ),
    ]
