# Generated by Django 4.2.13 on 2026-06-02 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatments', '0001_initial'),
        ('icd10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation_type', models.CharField(choices=[('MEDICATION', 'İlaç Sapması'), ('TIMING', 'Zamanlama Sapması'), ('PROCEDURE', 'Prosedür Sapması'), ('PROTOCOL_SKIP', 'Protokol Adımı Atlandı'), ('DOSAGE', 'Doz Sapması'), ('MONITORING', 'İzlem Eksikliği'), ('OTHER', 'Diğer')], max_length=20, verbose_name='Sapma Türü')),
                ('severity', models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('CRITICAL', 'Kritik')], default='WARNING', max_length=10, verbose_name='Ciddiyet')),
                ('description', models.TextField(help_text='Kural motorunun ürettiği otomatik açıklama', verbose_name='Sapma Açıklaması')),
                ('triggered_rule_id', models.CharField(blank=True, help_text='Örn: RULE_MED_001, RULE_TIMING_005', max_length=100, verbose_name='Tetikleyen Kural ID')),
                ('rule_output_data', models.JSONField(blank=True, default=dict, verbose_name='Kural Motoru Ham Çıktısı')),
                ('review_status', models.CharField(choices=[('PENDING', 'İnceleme Bekliyor'), ('CONFIRMED', 'Sapma Doğrulandı'), ('DISMISSED', 'Reddedildi (Sapma Değil)'), ('UNDER_REVIEW', 'İncelemede')], default='PENDING', max_length=15, verbose_name='İnceleme Durumu')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme Tarihi')),
                ('review_comment', models.TextField(blank=True, verbose_name='Uzman Görüşü / Açıklaması')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Tespit Tarihi')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deviation_logs', to='patients.admission', verbose_name='İlgili Yatış')),
                ('applied_protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deviations', to='treatments.appliedprotocol', verbose_name='Uygulanan Protokol')),
                ('reference_protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deviation_logs', to='icd10.treatmentprotocol', verbose_name='Referans Protokol')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations', to='patients.clinicalreport', verbose_name='İlgili Klinik Rapor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deviations', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen Uzman')),
            ],
            options={
                'verbose_name': 'Sapma Logu',
                'verbose_name_plural': 'Sapma Logları',
                'db_table': 'deviation_log',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='MalpracticeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('NONE', 'Risk Yok'), ('LOW', 'Düşük Risk'), ('MODERATE', 'Orta Risk'), ('HIGH', 'Yüksek Risk — Malpraktis Şüphesi'), ('CONFIRMED', 'Malpraktis Tespit Edildi')], default='NONE', max_length=15, verbose_name='Risk Seviyesi')),
                ('overall_compliance_score', models.FloatField(blank=True, null=True, verbose_name='Genel Uyum Skoru (%)')),
                ('automated_summary', models.TextField(blank=True, verbose_name='Otomatik Analiz Özeti')),
                ('expert_opinion', models.TextField(blank=True, verbose_name='Uzman Hekim Görüşü')),
                ('assessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Değerlendirme Tarihi')),
                ('finalized', models.BooleanField(default=False, help_text='True ise rapor hukuki belge niteliğindedir.', verbose_name='Sonuçlandırıldı mı?')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Sonuçlandırılma Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='malpractice_assessment', to='patients.admission', verbose_name='Yatış')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='Değerlendiren Uzman')),
                ('deviation_logs', models.ManyToManyField(blank=True, related_name='assessments', to='analysis.deviationlog', verbose_name='İlişkili Sapma Logları')),
            ],
            options={
                'verbose_name': 'Malpraktis Değerlendirmesi',
                'verbose_name_plural': 'Malpraktis Değerlendirmeleri',
                'db_table': 'malpractice_assessment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['risk_level'], name='malpractice_risk_le_5131fd_idx'), models.Index(fields=['finalized'], name='malpractice_finaliz_fbeffd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='deviationlog',
            index=models.Index(fields=['admission', 'severity'], name='deviation_l_admissi_26b9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlog',
            index=models.Index(fields=['review_status'], name='deviation_l_review__1e0574_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlog',
            index=models.Index(fields=['deviation_type'], name='deviation_l_deviati_58e594_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlog',
            index=models.Index(fields=['triggered_rule_id'], name='deviation_l_trigger_749796_idx'),
        ),
    ]
